# Generated by Django 3.2.25 on 2025-07-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.CharField(default='₹0', max_length=20),
            preserve_default=False,
        ),
    ]
